### ISSUE TITLE
unsigned comparison warning

### ISSUE THREAD

**Issue by MartinDelille** [joakimkarlsson/snowhouse#15]
When I try to compare two unsigned integer with the following code:

    AssertThat(PhTimeCode::bcdFromFrame(1, type), Equals(0x00000001));

I have the following warning:

    In file included from ../../../Joker/specs/SyncSpec/TimeCodeSpec.cpp:13:
    In file included from ../../../Joker/specs/PhSpec.h:7:
    In file included from ../../../Joker/vendor/bandit/bandit/bandit.h:23:
    In file included from ../../../Joker/vendor/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/snowhouse.h:22:
    In file included from ../../../Joker/vendor/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/constraints/constraints.h:12:
    ../../../Joker/vendor/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/constraints/equalsconstraint.h:25:26: warning: comparison of integers of different signs: 'const int' and 'const unsigned int' [-Wsign-compare]
      return (m_expected == actual);
              ~~~~~~~~~~ ^  ~~~~~~
    ../../../Joker/vendor/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/assert.h:77:15: note: in instantiation of function template specialization 'snowhouse::EqualsConstraint<int>::operator()<unsigned int>' requested here
         if (!expression(actual))
              ^
    ../../../Joker/specs/SyncSpec/TimeCodeSpec.cpp:110:5: note: in instantiation of function template specialization 'snowhouse::Assert::That<unsigned int, snowhouse::EqualsConstraint<int> >' requested here
                                AssertThat(PhTimeCode::bcdFromFrame(1, type), Equals(0x00000001));
                                ^
    ../../../Joker/vendor/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/assertmacro.h:13:11: note: expanded from macro 'AssertThat'
      Assert::That((p1), (p2), __FILE__, __LINE__);\
          ^
    1 warning generated.

I can get rid of it by casting the value like this:

    AssertThat((int)PhTimeCode::bcdFromFrame(1, type), Equals((int)0x00000001));

Is there a cleaner way to handle *unsigned int* ?

**Comment by nabijaczleweli** [comment]
Those code samples are byte-identical.
Yes, there is. Use `Equals(0x00000001u)`.

**Comment by MartinDelille** [comment]
Ok really simple, thanks!
I updated my code sample.

**Comment by nabijaczleweli** [comment]
Nota bene: this is purely a user-code problem, and is not influenced by any library code.

**Comment by MartinDelille** [comment]
Yes I just learned that `0x00000001` doesn't mean `unsigned`.
