### ISSUE TITLE
Modernize snowhouse

### ISSUE THREAD

**Issue by svenstaro** [joakimkarlsson/snowhouse#2]
It uses stuff that actually fails to compile like auto_ptr:

/tmp/bandit/bandit/assertion_frameworks/snowhouse/snowhouse/exceptions.h:59:109: error: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9.0/backward/auto_ptr.h:87) [-Werror=deprecated-declarations]

**Comment by joakimkarlsson** [comment]
Should be fixed as of v2.0.1 (b9bb2f2)
