### ISSUE TITLE
Add QString comparison

### ISSUE THREAD

**Issue by MartinDelille** [joakimkarlsson/snowhouse#5]
Since I'm using *Qt* I would like to make direct QString comparison without converting it to std::string explicitely. I would see two alternative to this:

- Add the possibility to make constraint with custom type (it is already possible to add new constraint)
- Add an optional set of instruction specific to Qt type like QString

**Comment by MartinDelille** [comment]
I come back with this issue: I understand that it is not a good idea to have *Qt* dependencies within snowhouse. A best solution would  be to have the ability to create its own assertion?
My spec are full of these: 
https://github.com/Phonations/Joker/blob/master/specs/StripSpec/StripDocSpec.cpp#L32

**Comment by joakimkarlsson** [comment]
Perhaps you could add an operator for comparing QString and std::string like this:

```cpp
bool operator==(const std::string& str, const QString& qstr)
{
    return str == mstr.toStdString();
};
```

That might allow the current equals operator to work out of the box.

**Comment by MartinDelille** [comment]
It works perfectly!
