### ISSUE TITLE
Does not build under MSVC

### ISSUE THREAD

**Issue by kawazoe** [joakimkarlsson/snowhouse#7]
MSVC doesn't support the noexcept keyword which is used since [this commit](https://github.com/joakimkarlsson/snowhouse/commit/e3c1d07da4cc9460c6941ae60a6e24a9cd65a4d3#diff-b4c32505a12cccbde5a6b762176be326R26) in the cxx11 branch. This prevents snowhouse (and thus bandit) to work in visual studio.

**Comment by joakimkarlsson** [comment]
Without noexcept, snowhouse won't compile properly in gcc and clang with paranoid compiler settings.

Perhaps, we'll have to resort to the following mess:

```cpp
#ifndef _MSC_VER
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif
```

**Comment by kawazoe** [comment]
You could also use the following to ignore the keyword on unsupported compilers. I would personally prefer this method since it does not require further code modifications when MSVC adds support for it later on.

```cpp
#ifdef _MSC_VER
#define noexcept
#endif
```
